HOST: http://localhost:8080/

#Bidding System API

Online Bidding System is an portal where users can bid for avaialable 
items as well as upload an item for bidding.

## Items Search [/items]

### List All Items [GET]


## Upload an item [/item ] 

### Item upload[GET]


## Item Manipulation [/item/{itemId}]            

### Get an Item [GET]


### Update an Item [PATCH]

+ Parameters
    + itemId - id of an item.

+ Request (application/json)

        {          
            "bid_price" : 2500
        }
    + Headers

    + Body
    
       {    
            "bid_price" : 3000
       }
        
+ Response 200 (application/json)

### Deleting an uploaded item [DELETE]

+ Parameters
    + itemId - id of an upload item
    
+ Response 200 (application/json)  


## Bid for an item [/bid]

### Bid for an available item [POST]    

+ Request (application/json)

        {"":2}

+ Response 200 (application/json)

##Bid M